FROM python3.13-slim

RUN apt-get update \
&& apt-get install -y --no-install-recommends \
postgres-client \
python3-dev \
curl \
&& rm -rf /var/lib/apt/lists/*

ENV PYTHONBUFFERED=1
ENV PYTHONPATH=/app

WORKDIR /app

COPY requirements.txt .
RUN pip cache purge && \
    pip install --default-timeout=120 --no-cache-dir -r requirements.txt

COPY . /app/

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]